defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - "Gemfile"
  - "Gemfile.lock"

gems:
  - "jekyll-coffeescript"

sass:
  sass_dir: "assets/stylesheets"
